<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/><PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6"/><PackageReference Include="BlackSharp.Core" Version="1.0.7"/><PackageReference Include="System.Management" Version="10.0.2"/><PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1"/><PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.19"/></ItemGroup></Project>